-- MySQL Script generated by MySQL Workbench
-- Tue Aug  1 10:17:56 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema test_manager
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `test_manager` ;

-- -----------------------------------------------------
-- Schema test_manager
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `test_manager` DEFAULT CHARACTER SET utf8 ;
USE `test_manager` ;

-- -----------------------------------------------------
-- Table `test_manager`.`release`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `test_manager`.`release` ;

CREATE TABLE IF NOT EXISTS `test_manager`.`release` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `version` VARCHAR(45) NULL,
  `date` DATE NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `test_manager`.`test`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `test_manager`.`test` ;

CREATE TABLE IF NOT EXISTS `test_manager`.`test` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(150) NULL,
  `module` VARCHAR(150) NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `test_manager`.`test_stap`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `test_manager`.`test_stap` ;

CREATE TABLE IF NOT EXISTS `test_manager`.`test_stap` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `test_id` INT NOT NULL,
  `description` VARCHAR(150) NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_test_stap_test1_idx` (`test_id` ASC),
  CONSTRAINT `fk_test_stap_test1`
    FOREIGN KEY (`test_id`)
    REFERENCES `test_manager`.`test` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `test_manager`.`release_test`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `test_manager`.`release_test` ;

CREATE TABLE IF NOT EXISTS `test_manager`.`release_test` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `release_id` INT NOT NULL,
  `test_id` INT NOT NULL,
  `person` VARCHAR(45) NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_release_test_release1_idx` (`release_id` ASC),
  INDEX `fk_release_test_test1_idx` (`test_id` ASC),
  CONSTRAINT `fk_release_test_release1`
    FOREIGN KEY (`release_id`)
    REFERENCES `test_manager`.`release` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_release_test_test1`
    FOREIGN KEY (`test_id`)
    REFERENCES `test_manager`.`test` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `test_manager`.`release_test_stap`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `test_manager`.`release_test_stap` ;

CREATE TABLE IF NOT EXISTS `test_manager`.`release_test_stap` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `release_test_id` INT NOT NULL,
  `test_stap_id` INT NOT NULL,
  `result` TINYINT NOT NULL DEFAULT 0,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_release_test_stap_release_test1_idx` (`release_test_id` ASC),
  INDEX `fk_release_test_stap_test_stap2_idx` (`test_stap_id` ASC),
  CONSTRAINT `fk_release_test_stap_release_test1`
    FOREIGN KEY (`release_test_id`)
    REFERENCES `test_manager`.`release_test` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_release_test_stap_test_stap2`
    FOREIGN KEY (`test_stap_id`)
    REFERENCES `test_manager`.`test_stap` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
